name: Publish package

on:
  create:

permissions:
  id-token: write
  contents: write

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: 'package.json'

      - name: Set release version env variables
        run: |
          export RELEASE_TAG_VERSION="$(echo "${{ github.ref }}" | grep -oP '(?<=refs/tags/v)\d+\.\d+\.\d+.*')"
          echo "RELEASE_TAG_VERSION=${RELEASE_TAG_VERSION}" >> $GITHUB_ENV
          export MAJOR_TAG_VERSION="$(echo ${RELEASE_TAG_VERSION} | grep -oP '^[^.]+').x"
          echo "MAJOR_TAG_VERSION=${MAJOR_TAG_VERSION}" >> $GITHUB_ENV

      - name: Ensure new version is mentioned in change log
        run: grep --regexp "\[v${RELEASE_TAG_VERSION}\]" CHANGELOG.md

      - name: Extract changelog for release
        run: awk -v ver=${RELEASE_TAG_VERSION} '/^#+ \[v/ { if (p) { exit }; if ($2 ~ "[v"ver"]") { p=1; next } } p' CHANGELOG.md > release-changelog.md

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test --maxWorkers=2

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.x'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          activate-environment: true

      - name: Install docs dependencies
        run: yarn install-docs-deps

      - name: Clean docs directories
        run: rm -rf site docs/api

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASS }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Set aliases
        run: |
          export LATEST_DOCS_VERSION="$(mike list | grep -oP '^.+(?= \[latest\])')"
          if [ -z "$LATEST_DOCS_VERSION" ]; then
            echo "ALIAS_LATEST=latest" >> $GITHUB_ENV
          else
            npx -y semver -r ">$LATEST_DOCS_VERSION" ${RELEASE_TAG_VERSION}
            if [ $? -eq 0 ]; then
              echo "ALIAS_LATEST=latest" >> $GITHUB_ENV
            fi
          fi
          export LATEST_DOCS_VERSION_FOR_MAJOR="$(mike list | grep -oP "^.+(?= \[$MAJOR_TAG_VERSION\])")"
          if [ -z "$LATEST_DOCS_VERSION_FOR_MAJOR" ]; then
            echo "ALIAS_MAJOR=$MAJOR_TAG_VERSION" >> $GITHUB_ENV
          else
            npx -y semver -r "^$LATEST_DOCS_VERSION_FOR_MAJOR" ${RELEASE_TAG_VERSION}
            if [ $? -eq 0 ]; then
              echo "ALIAS_MAJOR=$MAJOR_TAG_VERSION" >> $GITHUB_ENV
            fi
          fi

      - name: Build docs
        run: |
          yarn build-docs:assets
          yarn build-docs:api
          mike deploy -u ${RELEASE_TAG_VERSION} ${ALIAS_MAJOR} ${ALIAS_LATEST}
        env:
          VERSION: ${{ env.RELEASE_TAG_VERSION }}
          ALIAS: latest

      - name: Sign commit
        run: |
          git checkout gh-pages
          git commit --amend -S --no-edit
          git checkout ${{ github.ref }}

      - name: Set latest docs version
        run: mike set-default --push latest

      - name: Sign commit
        run: |
          git checkout gh-pages
          git commit --amend -S --no-edit
          git checkout ${{ github.ref }}

      - name: Build package
        run: yarn pack

      - name: Create release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          body_path: release-changelog.md
          files: package.tgz

      - name: Deploy docs
        run: git push origin gh-pages

      - name: Publish to registry
        run: |
          yarn config set npmAlwaysAuth true
          yarn npm publish
